"""HTML reporter — dark cyber theme."""
from jinja2 import Template
from datetime import datetime
from pathlib import Path


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>TH0RSC4N Report — {{ target }}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Courier New',monospace;background:#0a0e1a;color:#00ff88;padding:20px;line-height:1.6}
.container{max-width:1200px;margin:0 auto}
h1{color:#ff0044;border-bottom:2px solid #ff0044;padding-bottom:10px;margin-bottom:20px;text-shadow:0 0 15px #ff0044;font-size:2em}
h2{color:#00ccff;margin:25px 0 15px;border-left:4px solid #00ccff;padding-left:10px}
.meta{background:#1a1f2e;padding:15px;border-radius:5px;margin-bottom:20px;border-left:4px solid #00ff88}
.meta div{margin:5px 0;color:#ccc}
.meta strong{color:#00ff88}
.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;margin-bottom:30px}
.stat-card{background:#1a1f2e;padding:15px;border-left:4px solid;border-radius:5px;text-align:center}
.stat-card.critical{border-color:#ff0044}
.stat-card.high{border-color:#ff6600}
.stat-card.medium{border-color:#ffcc00}
.stat-card.low{border-color:#00ccff}
.stat-card.info{border-color:#666}
.stat-card.safe{border-color:#00ff88}
.stat-card .num{font-size:2em;font-weight:bold;color:#fff}
.stat-card .label{color:#888;font-size:.8em;text-transform:uppercase;letter-spacing:1px}
.category{margin:25px 0 15px;color:#00ccff;font-size:1.1em;border-bottom:1px dashed #00ccff;padding-bottom:5px}
.finding{background:#1a1f2e;padding:15px;margin-bottom:10px;border-left:4px solid;border-radius:5px}
.finding.CRITICAL{border-color:#ff0044}
.finding.HIGH{border-color:#ff6600}
.finding.MEDIUM{border-color:#ffcc00}
.finding.LOW{border-color:#00ccff}
.finding.INFO{border-color:#666}
.finding.SAFE{border-color:#00ff88}
.severity{display:inline-block;padding:2px 10px;border-radius:3px;font-size:.75em;font-weight:bold;margin-right:10px;letter-spacing:1px}
.severity.CRITICAL{background:#ff0044;color:#fff}
.severity.HIGH{background:#ff6600;color:#fff}
.severity.MEDIUM{background:#ffcc00;color:#000}
.severity.LOW{background:#00ccff;color:#000}
.severity.INFO{background:#666;color:#fff}
.severity.SAFE{background:#00ff88;color:#000}
.url-badge{color:#00ccff;font-size:.88em;margin-top:8px;padding:6px 10px;background:#0a1420;border-left:2px solid #00ccff;border-radius:3px;word-break:break-all;font-family:'Courier New',monospace}
.url-badge::before{content:'📍 ';margin-right:4px}
.mitigation{color:#ffcc00;font-size:.9em;margin-top:8px;padding-left:10px;border-left:2px solid #ffcc00}
.evidence{color:#666;font-size:.85em;margin-top:5px;font-style:italic;padding-left:10px}
.footer{text-align:center;color:#666;margin-top:40px;padding-top:20px;border-top:1px solid #333;font-size:.8em}
.footer strong{color:#ff0044}
</style>
</head>
<body>
<div class="container">
<h1>🛡️ TH0RSC4N SECURITY REPORT</h1>
<div class="meta">
<div><strong>Target:</strong> {{ target }}</div>
<div><strong>Scan Date:</strong> {{ date }}</div>
<div><strong>Total Findings:</strong> {{ findings|length }}</div>
<div><strong>Tool:</strong> TH0RSC4N v1.0.0 by Thorranov</div>
</div>

<h2><< SUMMARY >></h2>
<div class="stats">
<div class="stat-card critical"><div class="num">{{ stats.CRITICAL }}</div><div class="label">Critical</div></div>
<div class="stat-card high"><div class="num">{{ stats.HIGH }}</div><div class="label">High</div></div>
<div class="stat-card medium"><div class="num">{{ stats.MEDIUM }}</div><div class="label">Medium</div></div>
<div class="stat-card low"><div class="num">{{ stats.LOW }}</div><div class="label">Low</div></div>
<div class="stat-card info"><div class="num">{{ stats.INFO }}</div><div class="label">Info</div></div>
<div class="stat-card safe"><div class="num">{{ stats.SAFE }}</div><div class="label">Safe</div></div>
</div>

<h2><< FINDINGS >></h2>
{% for category, items in grouped.items() %}
<div class="category">>> {{ category }}</div>
{% for item in items %}
<div class="finding {{ item.severity }}">
<span class="severity {{ item.severity }}">{{ item.severity }}</span>
<span>{{ item.message }}</span>

{% if item.url and item.url != target %}
<div class="url-badge">{{ item.url }}</div>
{% endif %}

{% if item.mitigation %}
<div class="mitigation">↳ Mitigasi: {{ item.mitigation }}</div>
{% endif %}

{% if item.evidence %}
<div class="evidence">Evidence: {{ item.evidence }}</div>
{% endif %}
</div>
{% endfor %}
{% endfor %}

<div class="footer">
Generated by <strong>TH0RSC4N</strong> v1.0.0 | Brutal Security Scanner<br>
by <strong>Thorranov</strong> | Cyber Intelligence
</div>
</div>
</body>
</html>
"""


def report(findings, target, output_path):
    """Generate HTML report."""
    stats = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0, "SAFE": 0}
    grouped = {}

    for f in findings:
        stats[f.severity] = stats.get(f.severity, 0) + 1
        grouped.setdefault(f.category, []).append(f)

    # Render
    template = Template(HTML_TEMPLATE)
    html = template.render(
        target=target,
        findings=[f.to_dict() for f in findings],
        stats=stats,
        grouped={k: [f.to_dict() for f in v] for k, v in grouped.items()},
        date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )

    Path(output_path).write_text(html, encoding="utf-8")
    return output_path