from datetime import datetime

def report(findings, target, output_path):
    lines = [
        "# 🛡️ TH0RSC4N Security Report",
        "",
        f"**Target:** `{target}`  ",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  ",
        f"**Tool:** TH0RSC4N v1.0.0 by Thorranov",
        "",
        "## Summary",
        "",
    ]
    
    stats = {}
    for f in findings:
        stats[f.severity] = stats.get(f.severity, 0) + 1
    
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", "SAFE"]:
        lines.append(f"| {sev} | {stats.get(sev, 0)} |")
    lines.append("")
    
    # Findings
    grouped = {}
    for f in findings:
        grouped.setdefault(f.category, []).append(f)
    
    lines.append("## Findings")
    lines.append("")
    
    for cat, items in grouped.items():
        lines.append(f"### {cat}")
        lines.append("")
        for item in items:
            lines.append(f"- **[{item.severity}]** {item.message}")
            if item.mitigation:
                lines.append(f"  - ↳ *Mitigasi:* {item.mitigation}")
            if item.evidence:
                lines.append(f"  - Evidence: `{item.evidence}`")
        lines.append("")
    
    lines.append("---")
    lines.append("*Generated by TH0RSC4N v1.0.0 | by Thorranov*")
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    return output_path