"""TH0RSC4N - "Web Security OWASP 10 2025" by Thorranov | Security Researcher"""
__version__ = "1.0.0"
__author__ = "Thorranov"
__tool_name__ = "TH0RSC4N"
__tagline__ = "Web Security OWASP 10 2025"
__description__ = "60+ scenarios OWASP Top 10 2025 + Extra Vulnerabilities"
