"""Markdown reporter."""
from datetime import datetime


def report(findings, target, output_path):
    """Generate Markdown report."""
    lines = [
        "# 🛡️ TH0RSC4N Security Report",
        "",
        f"**Target:** `{target}`  ",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  ",
        f"**Tool:** TH0RSC4N v1.0.0 by Thorranov",
        "",
        "---",
        "",
        "## 📊 Summary",
        "",
    ]

    # Stats
    stats = {}
    for f in findings:
        stats[f.severity] = stats.get(f.severity, 0) + 1

    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", "SAFE"]:
        icon = {
            "CRITICAL": "🔴",
            "HIGH": "🟠",
            "MEDIUM": "🟡",
            "LOW": "🔵",
            "INFO": "⚪",
            "SAFE": "🟢",
        }.get(sev, "")
        lines.append(f"| {icon} {sev} | {stats.get(sev, 0)} |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Group by category
    grouped = {}
    for f in findings:
        grouped.setdefault(f.category, []).append(f)

    lines.append("## 🔍 Findings")
    lines.append("")

    for cat, items in grouped.items():
        lines.append(f"### {cat}")
        lines.append("")

        for item in items:
            # Header per finding
            lines.append(f"- **[{item.severity}]** {item.message}")

            # 📍 Affected URL
            if getattr(item, "url", None) and item.url.rstrip("/") != target.rstrip("/"):
                lines.append(f"  - **Affected URL:** `{item.url}`")

            # Mitigasi
            if item.mitigation:
                lines.append(f"  - *Mitigasi:* {item.mitigation}")

            # Evidence
            if item.evidence:
                ev = str(item.evidence).replace("`", "'")
                lines.append(f"  - Evidence: `{ev[:200]}`")

        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by **TH0RSC4N** v1.0.0 | by **Thorranov***")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return output_path
